package me.dvyy.nmr.parsing

import me.dvyy.nmr.complex.ComplexDouble
import me.dvyy.nmr.complex.ComplexDoubleArray
import me.dvyy.nmr.complex.toComplexArray
import java.io.File
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.io.path.div
import kotlin.math.ceil
import kotlin.math.log2
import kotlin.math.pow

/**
 * Parses the key-value pairs from a Bruker JCAMP-DX parameter file (e.g., 'acqus').
 */
class JcampDxParser {
    companion object {
        fun parse(file: File): Map<String, String> {
            val parameters = mutableMapOf<String, String>()
            if (!file.exists()) return parameters

            // Basic extraction: Matches lines like "##$BYTORDP= 0"
            // Note: In a production app, you may want to expand this to handle
            // multi-line array parameters (e.g., "(0..63)\n1.2 3.4 ...")
            file.forEachLine { line ->
                if (line.startsWith("##$")) {
                    val parts = line.substring(3).split("=", limit = 2)
                    if (parts.size == 2) {
                        parameters[parts[0].trim()] = parts[1].trim()
                    }
                }
            }
            return parameters
        }
    }
}

/**
 * Strongly typed data class holding the core parameters needed to parse the binary.
 */
data class AcquisitionParams(
    val timeDomainPoints: Int,     // TD (total real + imaginary points)
    val byteOrder: ByteOrder,      // BYTORDP
    val dataFormat: Int,           // DTYPA (0 = Int32, 2 = Float64)
    val numFids: Int = 1,           // TD from acqu2s (for 2D data)
)

/**
 * Main API for the End User to interact with a Bruker directory.
 *
 * Generated by Gemini 3.1 Pro
 */
class BrukerDataset(private val directoryPath: String) {
    private val dir = File(directoryPath)
    val name = dir.name

    private val procFile = dir.toPath() / "pdata" / "1" / "procs"

    init {
        require(dir.exists() && dir.isDirectory) { "Invalid Bruker directory: $directoryPath" }
    }

    // Lazy load the dictionaries so we don't parse files until needed
    val acqus: Map<String, String> by lazy { JcampDxParser.parse(File(dir, "acqus")) }
    val acqu2s: Map<String, String> by lazy { JcampDxParser.parse(File(dir, "acqu2s")) }
    val procs: Map<String, String> by lazy { JcampDxParser.parse(procFile.toFile()) }

    val totalSpectralWidth by lazy { procs["SW_p"]!!.toDouble() }
    val spectrometerFrequency by lazy { procs["SF"]!!.toDouble() }
    val offset by lazy { procs["OFFSET"]!!.toDouble() }

    // Strongly typed parameters extracted from the dictionary
    val params: AcquisitionParams by lazy {
        val td = acqus["TD"]?.toIntOrNull() ?: throw IllegalStateException("Missing TD in acqus")
        val bytordp = acqus["BYTORDP"]?.toIntOrNull() ?: 0
        val dtypa = acqus["DTYPA"]?.toIntOrNull() ?: 0

        // If 2D, acqu2s will contain the indirect dimension's TD
        val fids = acqu2s["TD"]?.toIntOrNull() ?: 1

        val order = if (bytordp == 0) ByteOrder.LITTLE_ENDIAN else ByteOrder.BIG_ENDIAN

        AcquisitionParams(
            timeDomainPoints = td,
            byteOrder = order,
            dataFormat = dtypa,
            numFids = fids
        )
    }

    /**
     * Reads the 1D 'fid' file and returns a Multik 1D array of ComplexDouble.
     */
    fun readFid(): ComplexDoubleArray {
        val fidFile = File(dir, "fid")
        require(fidFile.exists()) { "fid file not found in $directoryPath" }
        return readBinaryData(fidFile, pointsToRead = params.timeDomainPoints)
    }

    /**
     * Pre-built architecture for reading 2D data.
     * Reads the 'ser' file and slices it into a list of 1D Multik arrays.
     */
    fun readSer(): List<ComplexDoubleArray> {
        val serFile = File(dir, "ser")
        require(serFile.exists()) { "ser file not found in $directoryPath" }

        // A ser file is just N sequential FIDs.
        // For highly optimized 2D Multik arrays, you could output an Ndarray<ComplexDouble, D2>,
        // but returning a List<1D> is usually easier to process line-by-line initially.
        val totalPoints = params.timeDomainPoints * params.numFids
        val flatData = readBinaryData(serFile, pointsToRead = totalPoints)

        val complexPointsPerFid = params.timeDomainPoints / 2

        // Future mapping to a 2D array or returning the list of FIDs
        return flatData.toList().chunked(complexPointsPerFid) { chunk ->
            chunk.toComplexArray()
        }
    }

    /**
     * Internal generic binary reader using Java NIO.
     */
    private fun readBinaryData(file: File, pointsToRead: Int): ComplexDoubleArray {
        // Note: For massive 'ser' files (GBs), consider replacing readBytes()
        // with a FileChannel and MemoryMappedBuffer to avoid OOM exceptions.
        val bytes = file.readBytes()
        val buffer = ByteBuffer.wrap(bytes).order(params.byteOrder)

        val complexPoints = pointsToRead / 2
        val complexList = ComplexDoubleArray(complexPoints)

        // Bruker sequential complex points alternate: Real, Imag, Real, Imag...
        for (i in 0 until complexPoints) {
            val (re, im) = when (params.dataFormat) {
                0 -> buffer.int.toDouble() to buffer.int.toDouble() // Int32
                2 -> buffer.double to buffer.double                 // Float64
                else -> throw UnsupportedOperationException("Unsupported DTYPA: ${params.dataFormat}")
            }
            complexList[i] = ComplexDouble(re, im)
        }

        return complexList
    }
}

/**
 * Removes the Bruker digital filter delay by performing a circular left-shift.
 * Mimics `nmrglue.fileio.bruker.rm_dig_filter(..., truncate_grpdly=True)`.
 *
 * @param acqus The parsed acqus parameters map from your BrukerDataset.
 * @return A new Ndarray with the group delay shifted to the end.
 */
fun ComplexDoubleArray.removeDigitalFilter(acqus: Map<String, String>): ComplexDoubleArray {

    // 1. Look up the Group Delay.
    val grpdly = acqus["GRPDLY"]?.toDoubleOrNull()

    // If GRPDLY is missing or negative (common in legacy 1990s data),
    // nmrglue falls back to a lookup table using DECIM and DSPFVS.
    val shiftPoints: Int = if (grpdly != null && grpdly > 0.0) {
        grpdly.toInt()
    } else {
        val decim = acqus["DECIM"]?.toIntOrNull() ?: 1
        val dspfvs = acqus["DSPFVS"]?.toIntOrNull() ?: 12
        guessLegacyGroupDelay(decim, dspfvs).toInt()
    }

    // No shift required
    if (shiftPoints <= 0) return this

    // Prevent out-of-bounds if the shift somehow exceeds the array size
    val size = this.size
    val safeShift = shiftPoints % size

    // Pad to nearest power of two
    val exponent = ceil(log2(size.toDouble())).toInt()
    val paddedSize = 2.0.pow(exponent).toInt()
    val paddingCount = paddedSize - size

    // 2. Perform the circular left-shift (equivalent to np.roll(data, -shift))
    val shiftedData = ComplexDoubleArray(size)

    // Take elements from the 'shift' index to the end of the FID
    var index = 0
    for (i in safeShift until size) {
        shiftedData[index++] = this[i]
    }
    // Wrap the initial ring-up points to the end of the FID

//    for (i in 0 until safeShift) {
//        shiftedData.add(this[i])
//    }

    return shiftedData
}

/**
 * Partial fallback table mirroring nmrglue's `bruker_dsp_table`
 * for older TopSpin/XWIN-NMR data where GRPDLY isn't populated.
 */
private fun guessLegacyGroupDelay(decim: Int, dspfvs: Int): Double {
    return when (dspfvs) {
        12 -> when (decim) {
            16 -> 70.16
            32 -> 72.12
            64 -> 73.11
            else -> 70.0
        }
        // Add additional DSPFVS 10, 11, or 13 values here if you handle vintage data
        else -> 70.0
    }
}
