package me.dvyy.nmr.io.bruker

import me.dvyy.nmr.common.math.ComplexDouble
import me.dvyy.nmr.common.math.ComplexDoubleArray
import me.dvyy.nmr.common.math.toComplexArray
import java.io.File
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.io.path.div

/**
 * Main API for the End User to interact with a Bruker directory.
 *
 * Generated by Gemini 3.1 Pro
 */
class BrukerDataset(private val directoryPath: String) {
    private val dir = File(directoryPath)
    val path = dir.toPath()
    val name = dir.name

    private val procFile = dir.toPath() / "pdata" / "1" / "procs"

    init {
        require(dir.exists() && dir.isDirectory) { "Invalid Bruker directory: $directoryPath" }
    }

    // Lazy load the dictionaries so we don't parse files until needed
    val acqus: Map<String, String> by lazy { JcampDxParser.parse(path / "acqus") }
    val acqu2s: Map<String, String> by lazy { JcampDxParser.parse(path / "acqu2s") }
    val procs: Map<String, String> by lazy { JcampDxParser.parse(procFile) }

    val totalSpectralWidth by lazy { procs["SW_p"]!!.toDouble() }
    val spectrometerFrequency by lazy { procs["SF"]!!.toDouble() }
    val offset by lazy { procs["OFFSET"]!!.toDouble() }
    val widthPPM get() = totalSpectralWidth / spectrometerFrequency

    val numSamples by lazy { acqus["NS"]!!.toInt() }

    // Strongly typed parameters extracted from the dictionary
    val params: AcquisitionParams by lazy {
        val td = acqus["TD"]?.toIntOrNull() ?: throw IllegalStateException("Missing TD in acqus")
        val bytordp = acqus["BYTORDP"]?.toIntOrNull() ?: 0
        val dtypa = acqus["DTYPA"]?.toIntOrNull() ?: 0

        // If 2D, acqu2s will contain the indirect dimension's TD
        val fids = acqu2s["TD"]?.toIntOrNull() ?: 1

        val order = if (bytordp == 0) ByteOrder.LITTLE_ENDIAN else ByteOrder.BIG_ENDIAN

        AcquisitionParams(
            timeDomainPoints = td,
            byteOrder = order,
            dataFormat = dtypa,
            numFids = fids
        )
    }

    val is2D: Boolean get() = File(dir, "ser").exists()

    /**
     * Reads the 1D 'fid' file and returns a Multik 1D array of ComplexDouble.
     */
    fun readFid(): ComplexDoubleArray {
        val fidFile = File(dir, "fid")
        require(fidFile.exists()) { "fid file not found in $directoryPath" }
        return readBinaryData(fidFile, pointsToRead = params.timeDomainPoints)
    }

    /**
     * Pre-built architecture for reading 2D data.
     * Reads the 'ser' file and slices it into a list of 1D Multik arrays.
     */
    fun readSer(): List<ComplexDoubleArray> {
        val serFile = File(dir, "ser")
        require(serFile.exists()) { "ser file not found in $directoryPath" }

        // A ser file is just N sequential FIDs.
        // For highly optimized 2D Multik arrays, you could output an Ndarray<ComplexDouble, D2>,
        // but returning a List<1D> is usually easier to process line-by-line initially.
        val totalPoints = params.timeDomainPoints * params.numFids
        val flatData = readBinaryData(serFile, pointsToRead = totalPoints)

        val complexPointsPerFid = params.timeDomainPoints / 2

        // Future mapping to a 2D array or returning the list of FIDs
        return flatData.toList().chunked(complexPointsPerFid) { chunk ->
            chunk.toComplexArray()
        }
    }

    /**
     * Internal generic binary reader using Java NIO.
     */
    private fun readBinaryData(file: File, pointsToRead: Int): ComplexDoubleArray {
        // Note: For massive 'ser' files (GBs), consider replacing readBytes()
        // with a FileChannel and MemoryMappedBuffer to avoid OOM exceptions.
        val bytes = file.readBytes()
        val buffer = ByteBuffer.wrap(bytes).order(params.byteOrder)

        val complexPoints = pointsToRead / 2
        val complexList = ComplexDoubleArray(complexPoints)

        // Bruker sequential complex points alternate: Real, Imag, Real, Imag...
        for (i in 0 until complexPoints) {
            val (re, im) = when (params.dataFormat) {
                0 -> buffer.int.toDouble() to buffer.int.toDouble() // Int32
                2 -> buffer.double to buffer.double                 // Float64
                else -> throw UnsupportedOperationException("Unsupported DTYPA: ${params.dataFormat}")
            }
            complexList[i] = ComplexDouble(re, im)
        }

        return complexList
    }
}

